"""UI 所需的视图与动作能力；页面不知道旧字典和磁盘布局。"""

from typing import Any, Optional, Protocol

from pmsl.domain.states import Page
from pmsl.ui.models import CreationView, HomeView, PropertiesView, SettingsView
from pmsl.ui.scene_builder import Visuals


class SceneProvider(Protocol):
    @property
    def page(self) -> Page: ...
    @property
    def fps(self) -> int: ...
    @property
    def title(self) -> str: ...
    @property
    def clock(self) -> Any: ...
    @property
    def busy(self) -> bool: ...
    @property
    def should_exit(self) -> bool: ...
    @property
    def revision(self) -> int: ...
    @property
    def visuals(self) -> Visuals: ...
    def select(self, page: Page) -> None: ...
    def perform(self, action: str) -> None: ...
    def home_view(self) -> HomeView: ...
    def settings_view(self) -> SettingsView: ...
    def creation_view(self) -> CreationView: ...
    def properties_view(self) -> PropertiesView: ...
    def open_link(self, name: str) -> None: ...
    def remember_view(self) -> None: ...
    def restore_view(self) -> None: ...
    def update(self) -> None: ...
    def handle_console_event(self, event: Any) -> None: ...
    def draw_background(self, surface: Any) -> None: ...
    def draw_overlays(self, surface: Any) -> None: ...
    def confirm(self, *args: Any, **kwargs: Any) -> Optional[str]: ...
    def request_exit(self) -> bool: ...
