"""登记内置图片和字体的资源路径，供界面加载与打包使用。"""

from typing import Dict

FONT_FILE = "fonts/HarmonyOS_Sans_SC_Bold.ttf"
FONT_SIZES = (10, 15, 18, 20, 25, 28, 30, 35, 40, 45, 55)
IMAGE_FILES: Dict[str, str] = {
    "fabric_logo": "imgs/All_icon/fabric_logo.png",
    "forge_logo": "imgs/All_icon/forge_logo.png",
    "mod": "imgs/All_icon/mod.png",
    "neoforge_logo": "imgs/All_icon/neoforge_logo.png",
    "papermc_logo": "imgs/All_icon/papermc_logo.png",
    "plugin": "imgs/All_icon/plugin.png",
    "spigot_logo": "imgs/All_icon/spigot_logo.png",
    "b_bg_title_main": "imgs/Background/b_bg_title_main.png",
    "b_bg_title_main_2": "imgs/Background/b_bg_title_main_2.png",
    "bg_theend_re": "imgs/Background/bg_theend_re.png",
    "button_text": "imgs/Background/button_text.png",
    "server_name": "imgs/Background/server_name.png",
    "server_pt": "imgs/Background/server_pt.png",
    "serverchange": "imgs/Background/serverchange.png",
    "serverchange_bg": "imgs/Background/serverchange_bg.png",
    "serverlist": "imgs/Background/serverlist.png",
    "title_winter": "imgs/Background/title_winter.png",
    "b_back": "imgs/Buttons/b_back.png",
    "b_back_to_main": "imgs/Buttons/b_back_to_main.png",
    "b_bg": "imgs/Buttons/b_bg.png",
    "b_bg_2": "imgs/Buttons/b_bg_2.png",
    "b_bg_3": "imgs/Buttons/b_bg_3.png",
    "b_false": "imgs/Buttons/b_false.png",
    "b_next": "imgs/Buttons/b_next.png",
    "b_re_icon": "imgs/Buttons/b_re_icon.png",
    "b_re_name": "imgs/Buttons/b_re_name.png",
    "b_title": "imgs/Buttons/b_title.png",
    "b_title_back": "imgs/Buttons/b_title_back.png",
    "b_title_next": "imgs/Buttons/b_title_next.png",
    "b_true": "imgs/Buttons/b_true.png",
    "clone": "imgs/Buttons/clone.png",
    "lod_s": "imgs/Buttons/lod_s.png",
    "about_authors": "imgs/Program_Author/about_authors.png",
    "authors_1": "imgs/Program_Author/authors_1.png",
    "Loading": "imgs/Sub_interfaces/Loading.png",
    "create_server_1": "imgs/Sub_interfaces/create_server_1.png",
    "create_server_2": "imgs/Sub_interfaces/create_server_2.png",
    "create_server_3": "imgs/Sub_interfaces/create_server_3.png",
    "create_server_4": "imgs/Sub_interfaces/create_server_4.png",
    "create_server_5": "imgs/Sub_interfaces/create_server_5.png",
    "eula_1": "imgs/Sub_interfaces/eula_1.png",
    "finish": "imgs/Sub_interfaces/finish.png",
    "op_server_1": "imgs/Sub_interfaces/op_server_1.png",
    "op_server_2": "imgs/Sub_interfaces/op_server_2.png",
    "pgm_setting_1": "imgs/Sub_interfaces/pgm_setting_1.png",
    "pgm_setting_2": "imgs/Sub_interfaces/pgm_setting_2.png",
    "pgm_setting_3": "imgs/Sub_interfaces/pgm_setting_3.png",
    "set_server": "imgs/Sub_interfaces/set_server.png",
    "set_world": "imgs/Sub_interfaces/set_world.png",
    "w_tip": "imgs/Sub_interfaces/w_tip.png",
    "bg": "imgs/bg.png",
    "choosef": "imgs/choosef.png",
    "github": "imgs/github.png",
    "icon": "imgs/icon.png",
    "lg": "imgs/lg.png",
    "list": "imgs/list.png",
    "running_list": "imgs/running_list.png",
}
